meta_product_name: "Robert & Romane"
meta_title: "Robert & Romane - Quality time shared between seniors and students"
meta_description: "R&R takes a different approach on aging by connecting fun and energetic students to seniors who need transportation, house help, technology lessons, companionship, and other senior services."
meta_image: "cover.png"
twitter_account: "@robert&romane_twitter_account"
